# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch

# Create random tensor
r_tens=torch.rand(7,7)
r_tens

tensor([[0.3201, 0.9028, 0.8516, 0.4830, 0.4432, 0.2059, 0.8171],
        [0.2331, 0.6556, 0.2223, 0.7915, 0.7822, 0.2582, 0.4411],
        [0.6698, 0.4091, 0.5312, 0.7774, 0.8511, 0.9177, 0.1865],
        [0.9178, 0.6428, 0.8176, 0.5957, 0.8700, 0.9436, 0.5907],
        [0.1518, 0.7080, 0.3158, 0.2706, 0.8275, 0.1593, 0.0591],
        [0.2324, 0.9070, 0.6498, 0.3083, 0.9735, 0.3112, 0.4872],
        [0.7282, 0.9873, 0.8005, 0.9572, 0.1657, 0.5484, 0.5285]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [6]:
# Create another random tensor
r_tens2=torch.rand(size=(1,7))

# Perform matrix multiplication 
torch.mm(r_tens,r_tens2.T)

tensor([[1.1173],
        [1.7231],
        [1.4061],
        [1.9499],
        [0.9564],
        [1.3146],
        [1.1037]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [5]:
# Set manual seed
RANDOM_SEED=0
torch.manual_seed(RANDOM_SEED)

# Create two random tensors
r_tens=torch.rand(7,7)
torch.manual_seed(RANDOM_SEED)
r_tens2=torch.rand(1,7)

# Matrix multiply tensors
r_tens@r_tens2.T

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [7]:
# Set random seed on the GPU
RANDOM_SEED=1234
torch.mps.manual_seed(RANDOM_SEED)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [24]:
# Set random seed
torch.mps.manual_seed(RANDOM_SEED)
# Check for access to GPU
device='cuda' if torch.cuda.is_available() else 'mps'
# Create two random tensors on GPU
torch.manual_seed(RANDOM_SEED)
r_tens=torch.rand(2,3).to(device)
# torch.manual_seed(RANDOM_SEED)
r_tens2=torch.rand(2,3).to(device)
device,r_tens,r_tens2

('mps',
 tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='mps:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='mps:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [28]:
# Perform matmul on tensor_A and tensor_B
rm=torch.matmul(r_tens,r_tens2.T)

### 8. Find the maximum and minimum values of the output of 7.

In [29]:
# Find max
print(torch.max(rm))

# Find min
print(torch.min(rm))


tensor(0.5617, device='mps:0')
tensor(0.3647, device='mps:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [30]:
# Find arg max
print(torch.argmax(rm))

# Find arg min
print(torch.argmin(rm))


tensor(3, device='mps:0')
tensor(0, device='mps:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [31]:
# Set seed
RANDOM_SEED=7
torch.manual_seed(RANDOM_SEED)

# Create random tensor
r_tens=torch.rand(1,1,1,10)

# Remove single dimensions
r_tens2=torch.squeeze_copy(r_tens)
# Print out tensors and their shapes
r_tens,r_tens2,r_tens.shape,r_tens2.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([1, 1, 1, 10]),
 torch.Size([10]))